service: simple-aws-lambda

provider:
  name: aws
  runtime: java11
  profile: serverless-admin
  stage: api
  region: us-east-1
  timeout: 10
  memorySize: 1024
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.myBucket}/*'
        - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]
  apiGateway:
    shouldStartNameWithService: true

custom:
  myBucket: serverless-bucket-puppi

package:
  artifact: target/simple-aws-lambda.jar

functions:
  simpleHttp:
    handler: com.spuppi.aws.Function
    events:
      - http:
          method: POST
          path: /simplehttp
          request:
            template:
              application/json: $input.json('$')
